name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.prettierrc'
      - '**/*ignore'
  push:
    branches:
      - master
      - next
      - rc
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.prettierrc'
      - '**/*ignore'

jobs:
  test:
    name: Unit + Type Check / Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm clean-install

      - name: Type Check
        run: npm run test:types

      - name: Run Unit Tests + Coverage
        run: npm run test:coverage

      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./test/coverage/lcov.info

  deno-tests:
    name: Deno Tests / ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['1.x', '2.x']
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Run Deno Tests
        run: |
          npm clean-install
          npm run build
          cd test/deno
          npm install
          npm test || npm test

      - name: Run integration and browser tests on Deno 2.x only
        if: ${{ matrix.deno == '2.x' }}
        run: |
          npm run test:integration:browser

      - name: Stop Supabase
        run: supabase stop

  node-integration:
    name: Node Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Run integration tests
        run: |
          # Remove pnpm-lock.yaml to ensure npm uses only package-lock.json
          rm -f pnpm-lock.yaml
          # Force install specific version of realtime-js
          npm install @supabase/realtime-js@2.11.13 --save-exact
          # Aggressive cache cleaning to ensure we use package-lock.json version
          npm cache clean --force
          rm -rf node_modules
          rm -rf ~/.npm
          npm clean-install
          npm run build
          npm run test:integration || npm run test:integration

      - name: Stop Supabase
        run: supabase stop

  next-integration:
    name: Next.js Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - name: Run integration tests
        run: |
          npm clean-install
          npm run build
          PKG=$(npm pack)
          echo "Packed: $PKG"
          cd test/integration/next
          npm install "../../../$PKG"
          npm install
          npx playwright install
          npm run test

      - name: Stop Supabase
        run: supabase stop

  expo-tests:
    name: Expo Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: |
          supabase start

      - name: Build and test expo
        run: |
          npm clean-install
          npm run build
          PKG=$(npm pack)
          echo "Packed: $PKG"
          cd test/integration/expo
          npm install "../../../$PKG"
          npm install
          npm test || npm test

      - name: Stop Supabase
        run: supabase stop

  websocket-browser-tests:
    name: WebSocket Browser Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - name: Start Supabase
        run: supabase start

      - name: Run WebSocket tests
        run: |
          echo "=== Initial package-lock.json realtime-js version ==="
          grep -A 2 -B 2 "realtime-js" package-lock.json
          # Remove pnpm-lock.yaml to ensure npm uses only package-lock.json
          rm -f pnpm-lock.yaml
          # Force install specific version of realtime-js
          npm install @supabase/realtime-js@2.11.13 --save-exact
          echo "=== After npm install --save-exact ==="
          grep -A 2 -B 2 "realtime-js" package-lock.json
          # Aggressive cache cleaning to ensure we use package-lock.json version
          npm cache clean --force
          rm -rf node_modules
          rm -rf ~/.npm
          npm clean-install
          echo "=== After npm clean-install ==="
          grep -A 2 -B 2 "realtime-js" package-lock.json
          npm run build
          echo "=== Checking realtime-js version ==="
          npm list @supabase/realtime-js
          echo "=== Checking package-lock.json ==="
          grep -A 5 -B 5 "realtime-js" package-lock.json
          echo "=== Checking all realtime-js versions in node_modules ==="
          find node_modules -name "package.json" -exec grep -l "realtime-js" {} \; | head -10
          echo "=== Checking why realtime-js 2.11.15 is installed ==="
          npm ls @supabase/realtime-js --depth=10
          echo "=== UMD file info ==="
          ls -la dist/umd/
          echo "=== Running WebSocket tests ==="
          cd test/integration/websocket
          npm install
          cp ../../../dist/umd/supabase.js .
          npm run test

      - name: Stop Supabase
        run: supabase stop
